package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbAdmDocentesxnucleo generated by hbm2java
 */
public class TbAdmDocentesxnucleo implements java.io.Serializable {

	private int nbId;
	private TbAdmNucleo tbAdmNucleo;
	private TbAdmPersona tbAdmPersona;
	private String vrModusuario;
	private Date vrModfecha;

	public TbAdmDocentesxnucleo() {
	}

	public TbAdmDocentesxnucleo(int nbId, TbAdmNucleo tbAdmNucleo,
			TbAdmPersona tbAdmPersona) {
		this.nbId = nbId;
		this.tbAdmNucleo = tbAdmNucleo;
		this.tbAdmPersona = tbAdmPersona;
	}

	public TbAdmDocentesxnucleo(int nbId, TbAdmNucleo tbAdmNucleo,
			TbAdmPersona tbAdmPersona, String vrModusuario, Date vrModfecha) {
		this.nbId = nbId;
		this.tbAdmNucleo = tbAdmNucleo;
		this.tbAdmPersona = tbAdmPersona;
		this.vrModusuario = vrModusuario;
		this.vrModfecha = vrModfecha;
	}

	public int getNbId() {
		return this.nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public TbAdmNucleo getTbAdmNucleo() {
		return this.tbAdmNucleo;
	}

	public void setTbAdmNucleo(TbAdmNucleo tbAdmNucleo) {
		this.tbAdmNucleo = tbAdmNucleo;
	}

	public TbAdmPersona getTbAdmPersona() {
		return this.tbAdmPersona;
	}

	public void setTbAdmPersona(TbAdmPersona tbAdmPersona) {
		this.tbAdmPersona = tbAdmPersona;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getVrModfecha() {
		return this.vrModfecha;
	}

	public void setVrModfecha(Date vrModfecha) {
		this.vrModfecha = vrModfecha;
	}

}
