package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmPersona generated by hbm2java
 */
public class TbAdmPersona implements java.io.Serializable {

	private String vrIdpersona;
	private TbAdmTipopersona tbAdmTipopersona;
	private TbAdmCiudad tbAdmCiudad;
	private TbAdmTipoidentificacion tbAdmTipoidentificacion;
	private String vrNombres;
	private String vrApellidos;
	private String vrEmail;
	private String vrTelefono;
	private int blEstado;
	private String vrModusuario;
	private Date dtModfecha;
	private Set tbAdmUsuarioses = new HashSet(0);
	private Set tbAdmDocentesxnucleos = new HashSet(0);

	public TbAdmPersona() {
	}

	public TbAdmPersona(String vrIdpersona, TbAdmTipopersona tbAdmTipopersona,
			TbAdmCiudad tbAdmCiudad,
			TbAdmTipoidentificacion tbAdmTipoidentificacion, String vrNombres,
			String vrApellidos) {
		this.vrIdpersona = vrIdpersona;
		this.tbAdmTipopersona = tbAdmTipopersona;
		this.tbAdmCiudad = tbAdmCiudad;
		this.tbAdmTipoidentificacion = tbAdmTipoidentificacion;
		this.vrNombres = vrNombres;
		this.vrApellidos = vrApellidos;
	}

	public TbAdmPersona(String vrIdpersona, TbAdmTipopersona tbAdmTipopersona,
			TbAdmCiudad tbAdmCiudad,
			TbAdmTipoidentificacion tbAdmTipoidentificacion, String vrNombres,
			String vrApellidos, String vrEmail, String vrTelefono,
			int blEstado, String vrModusuario, Date dtModfecha,
			Set tbAdmUsuarioses, Set tbAdmDocentesxnucleos) {
		this.vrIdpersona = vrIdpersona;
		this.tbAdmTipopersona = tbAdmTipopersona;
		this.tbAdmCiudad = tbAdmCiudad;
		this.tbAdmTipoidentificacion = tbAdmTipoidentificacion;
		this.vrNombres = vrNombres;
		this.vrApellidos = vrApellidos;
		this.vrEmail = vrEmail;
		this.vrTelefono = vrTelefono;
		this.blEstado = blEstado;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
		this.tbAdmUsuarioses = tbAdmUsuarioses;
		this.tbAdmDocentesxnucleos = tbAdmDocentesxnucleos;
	}

	public String getVrIdpersona() {
		return this.vrIdpersona;
	}

	public void setVrIdpersona(String vrIdpersona) {
		this.vrIdpersona = vrIdpersona;
	}

	public TbAdmTipopersona getTbAdmTipopersona() {
		return this.tbAdmTipopersona;
	}

	public void setTbAdmTipopersona(TbAdmTipopersona tbAdmTipopersona) {
		this.tbAdmTipopersona = tbAdmTipopersona;
	}

	public TbAdmCiudad getTbAdmCiudad() {
		return this.tbAdmCiudad;
	}

	public void setTbAdmCiudad(TbAdmCiudad tbAdmCiudad) {
		this.tbAdmCiudad = tbAdmCiudad;
	}

	public TbAdmTipoidentificacion getTbAdmTipoidentificacion() {
		return this.tbAdmTipoidentificacion;
	}

	public void setTbAdmTipoidentificacion(
			TbAdmTipoidentificacion tbAdmTipoidentificacion) {
		this.tbAdmTipoidentificacion = tbAdmTipoidentificacion;
	}

	public String getVrNombres() {
		return this.vrNombres;
	}

	public void setVrNombres(String vrNombres) {
		this.vrNombres = vrNombres;
	}

	public String getVrApellidos() {
		return this.vrApellidos;
	}

	public void setVrApellidos(String vrApellidos) {
		this.vrApellidos = vrApellidos;
	}

	public String getVrEmail() {
		return this.vrEmail;
	}

	public void setVrEmail(String vrEmail) {
		this.vrEmail = vrEmail;
	}

	public String getVrTelefono() {
		return this.vrTelefono;
	}

	public void setVrTelefono(String vrTelefono) {
		this.vrTelefono = vrTelefono;
	}

	public int getBlEstado() {
		return this.blEstado;
	}

	public void setBlEstado(int blEstado) {
		this.blEstado = blEstado;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

	public Set getTbAdmUsuarioses() {
		return this.tbAdmUsuarioses;
	}

	public void setTbAdmUsuarioses(Set tbAdmUsuarioses) {
		this.tbAdmUsuarioses = tbAdmUsuarioses;
	}

	public Set getTbAdmDocentesxnucleos() {
		return this.tbAdmDocentesxnucleos;
	}

	public void setTbAdmDocentesxnucleos(Set tbAdmDocentesxnucleos) {
		this.tbAdmDocentesxnucleos = tbAdmDocentesxnucleos;
	}

}
