package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbAdmCorrequisitos generated by hbm2java
 */
public class TbAdmCorrequisitos implements java.io.Serializable {

	private int nbId;
	private TbAdmMaterias tbAdmMateriasByVrMateria;
	private TbAdmMaterias tbAdmMateriasByVrCorrequisito;
	private String vrModusuario;
	private Date dtModfecha;

	public TbAdmCorrequisitos() {
	}

	public TbAdmCorrequisitos(int nbId,
			TbAdmMaterias tbAdmMateriasByVrMateria,
			TbAdmMaterias tbAdmMateriasByVrCorrequisito) {
		this.nbId = nbId;
		this.tbAdmMateriasByVrMateria = tbAdmMateriasByVrMateria;
		this.tbAdmMateriasByVrCorrequisito = tbAdmMateriasByVrCorrequisito;
	}

	public TbAdmCorrequisitos(int nbId,
			TbAdmMaterias tbAdmMateriasByVrMateria,
			TbAdmMaterias tbAdmMateriasByVrCorrequisito, String vrModusuario,
			Date dtModfecha) {
		this.nbId = nbId;
		this.tbAdmMateriasByVrMateria = tbAdmMateriasByVrMateria;
		this.tbAdmMateriasByVrCorrequisito = tbAdmMateriasByVrCorrequisito;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}

	public int getNbId() {
		return this.nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public TbAdmMaterias getTbAdmMateriasByVrMateria() {
		return this.tbAdmMateriasByVrMateria;
	}

	public void setTbAdmMateriasByVrMateria(
			TbAdmMaterias tbAdmMateriasByVrMateria) {
		this.tbAdmMateriasByVrMateria = tbAdmMateriasByVrMateria;
	}

	public TbAdmMaterias getTbAdmMateriasByVrCorrequisito() {
		return this.tbAdmMateriasByVrCorrequisito;
	}

	public void setTbAdmMateriasByVrCorrequisito(
			TbAdmMaterias tbAdmMateriasByVrCorrequisito) {
		this.tbAdmMateriasByVrCorrequisito = tbAdmMateriasByVrCorrequisito;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

}
