package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmDepartamentos generated by hbm2java
 */
public class TbAdmDepartamento implements java.io.Serializable {

	private int nbIddepartamento;
	private TbAdmPais tbAdmPais;
	private String vrNombres;
	private String vrModusuario;
	private Date dtModfecha;
	private Set tbAdmCiudad = new HashSet(0);

	public TbAdmDepartamento() {
	}

	public TbAdmDepartamento(int nbIddepartamento,
			TbAdmPais tbAdmPais) {
		this.nbIddepartamento = nbIddepartamento;
		this.tbAdmPais = tbAdmPais;
	}

	public TbAdmDepartamento(int nbIddepartamento,
			TbAdmPais tbAdmPais, String vrNombres, String vrModusuario,
			Date dtModfecha, Set tbAdmCiudad) {
		this.nbIddepartamento = nbIddepartamento;
		this.tbAdmPais = tbAdmPais;
		this.vrNombres = vrNombres;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
		this.tbAdmCiudad = tbAdmCiudad;
	}

	public int getNbIddepartamento() {
		return this.nbIddepartamento;
	}

	public void setNbIddepartamento(int nbIddepartamento) {
		this.nbIddepartamento = nbIddepartamento;
	}

	public TbAdmPais getTbAdmPais() {
		return this.tbAdmPais;
	}

	public void setTbAdmPais(TbAdmPais tbAdmPais) {
		this.tbAdmPais = tbAdmPais;
	}

	public String getVrNombres() {
		return this.vrNombres;
	}

	public void setVrNombres(String vrNombres) {
		this.vrNombres = vrNombres;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

	public Set getTbAdmCiudad() {
		return this.tbAdmCiudad;
	}

	public void setTbAdmCiudad(Set tbAdmCiudad) {
		this.tbAdmCiudad = tbAdmCiudad;
	}

}
