package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmDependencia generated by hbm2java
 */
public class TbAdmDependencia implements java.io.Serializable {

	private String vrIddependencia;
	private TbAdmUnidadAcademica tbAdmUnidadAcademica;
	private String vrNombre;
	private String vrModusuario;
	private Date dtModfecha;
	private Set tbAdmNucleos = new HashSet(0);

	public TbAdmDependencia() {
	}

	public TbAdmDependencia(String vrIddependencia,
			TbAdmUnidadAcademica tbAdmUnidadAcademica) {
		this.vrIddependencia = vrIddependencia;
		this.tbAdmUnidadAcademica = tbAdmUnidadAcademica;
	}

	public TbAdmDependencia(String vrIddependencia,
			TbAdmUnidadAcademica tbAdmUnidadAcademica, String vrNombre,
			String vrModusuario, Date dtModfecha, Set tbAdmNucleos) {
		this.vrIddependencia = vrIddependencia;
		this.tbAdmUnidadAcademica = tbAdmUnidadAcademica;
		this.vrNombre = vrNombre;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
		this.tbAdmNucleos = tbAdmNucleos;
	}

	public String getVrIddependencia() {
		return this.vrIddependencia;
	}

	public void setVrIddependencia(String vrIddependencia) {
		this.vrIddependencia = vrIddependencia;
	}

	public TbAdmUnidadAcademica getTbAdmUnidadAcademica() {
		return this.tbAdmUnidadAcademica;
	}

	public void setTbAdmUnidadAcademica(
			TbAdmUnidadAcademica tbAdmUnidadAcademica) {
		this.tbAdmUnidadAcademica = tbAdmUnidadAcademica;
	}

	public String getVrNombre() {
		return this.vrNombre;
	}

	public void setVrNombre(String vrNombre) {
		this.vrNombre = vrNombre;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

	public Set getTbAdmNucleos() {
		return this.tbAdmNucleos;
	}

	public void setTbAdmNucleos(Set tbAdmNucleos) {
		this.tbAdmNucleos = tbAdmNucleos;
	}

}
