package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbAdmPrerrequisitos generated by hbm2java
 */
public class TbAdmPrerrequisitos implements java.io.Serializable {

	private int nbId;
	private TbAdmMaterias tbAdmMateriasByVrMateria;
	private TbAdmMaterias tbAdmMateriasByVrPrerrequisito;
	private String vrModusuario;
	private Date dtModfecha;

	public TbAdmPrerrequisitos() {
	}

	public TbAdmPrerrequisitos(int nbId,
			TbAdmMaterias tbAdmMateriasByVrMateria,
			TbAdmMaterias tbAdmMateriasByVrPrerrequisito, String vrModusuario) {
		this.nbId = nbId;
		this.tbAdmMateriasByVrMateria = tbAdmMateriasByVrMateria;
		this.tbAdmMateriasByVrPrerrequisito = tbAdmMateriasByVrPrerrequisito;
		this.vrModusuario = vrModusuario;
	}

	public TbAdmPrerrequisitos(int nbId,
			TbAdmMaterias tbAdmMateriasByVrMateria,
			TbAdmMaterias tbAdmMateriasByVrPrerrequisito, String vrModusuario,
			Date dtModfecha) {
		this.nbId = nbId;
		this.tbAdmMateriasByVrMateria = tbAdmMateriasByVrMateria;
		this.tbAdmMateriasByVrPrerrequisito = tbAdmMateriasByVrPrerrequisito;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}

	public int getNbId() {
		return this.nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public TbAdmMaterias getTbAdmMateriasByVrMateria() {
		return this.tbAdmMateriasByVrMateria;
	}

	public void setTbAdmMateriasByVrMateria(
			TbAdmMaterias tbAdmMateriasByVrMateria) {
		this.tbAdmMateriasByVrMateria = tbAdmMateriasByVrMateria;
	}

	public TbAdmMaterias getTbAdmMateriasByVrPrerrequisito() {
		return this.tbAdmMateriasByVrPrerrequisito;
	}

	public void setTbAdmMateriasByVrPrerrequisito(
			TbAdmMaterias tbAdmMateriasByVrPrerrequisito) {
		this.tbAdmMateriasByVrPrerrequisito = tbAdmMateriasByVrPrerrequisito;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

}
