package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbMicMicroxsemestre generated by hbm2java
 */
public class TbMicMicroxsemestre implements java.io.Serializable {

	private int nbId;
	private TbMicMicrocurriculos tbMicMicrocurriculos;
	private TbAdmSemestre tbAdmSemestre;
	private String vrModusuario;
	private Date dtModfecha;

	public TbMicMicroxsemestre() {
	}

	public TbMicMicroxsemestre(int nbId,
			TbMicMicrocurriculos tbMicMicrocurriculos,
			TbAdmSemestre tbAdmSemestre) {
		this.nbId = nbId;
		this.tbMicMicrocurriculos = tbMicMicrocurriculos;
		this.tbAdmSemestre = tbAdmSemestre;
	}

	public TbMicMicroxsemestre(int nbId,
			TbMicMicrocurriculos tbMicMicrocurriculos,
			TbAdmSemestre tbAdmSemestre, String vrModusuario, Date dtModfecha) {
		this.nbId = nbId;
		this.tbMicMicrocurriculos = tbMicMicrocurriculos;
		this.tbAdmSemestre = tbAdmSemestre;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}

	public int getNbId() {
		return this.nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public TbMicMicrocurriculos getTbMicMicrocurriculos() {
		return this.tbMicMicrocurriculos;
	}

	public void setTbMicMicrocurriculos(
			TbMicMicrocurriculos tbMicMicrocurriculos) {
		this.tbMicMicrocurriculos = tbMicMicrocurriculos;
	}

	public TbAdmSemestre getTbAdmSemestre() {
		return this.tbAdmSemestre;
	}

	public void setTbAdmSemestre(TbAdmSemestre tbAdmSemestre) {
		this.tbAdmSemestre = tbAdmSemestre;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

}
