package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbMicMateriasxpensum generated by hbm2java
 */
public class TbMicMateriaxpensum implements java.io.Serializable {

	private int nbId;
	private TbAdmMateria tbAdmMateria;
	private TbMicPensum tbMicPensum;
	private String vrModusuario;
	private Date dtModfecha;


	public TbMicMateriaxpensum(TbAdmMateria tbAdmMateria, TbMicPensum tbMicPensum) {
		this.tbAdmMateria = tbAdmMateria;
		this.tbMicPensum = tbMicPensum;
	}

	public TbMicMateriaxpensum(TbAdmMateria tbAdmMateria, TbMicPensum tbMicPensum, 
			String vrModusuario, Date dtModfecha) {
		this.tbAdmMateria = tbAdmMateria;
		this.tbMicPensum = tbMicPensum;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}

	public int getNbId() {
		return this.nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public TbAdmMateria getTbAdmMateria() {
		return this.tbAdmMateria;
	}

	public void setTbAdmMateria(TbAdmMateria tbAdmMateria) {
		this.tbAdmMateria = tbAdmMateria;
	}

	public TbMicPensum getTbMicPensum() {
		return this.tbMicPensum;
	}

	public void setTbMicPensum(TbMicPensum tbMicPensum) {
		this.tbMicPensum = tbMicPensum;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

}
