package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbMicTemasxunidad generated by hbm2java
 */
public class TbMicTemasxunidad implements java.io.Serializable {

	private int nbId;
	private TbMicUnidades tbMicUnidades;
	private TbMicTemas tbMicTemas;
	private int nbSemanasRequeridas;
	private String vrModusuario;
	private Date dtModfecha;

	public TbMicTemasxunidad() {
	}

	public TbMicTemasxunidad(int nbId, TbMicUnidades tbMicUnidades,
			TbMicTemas tbMicTemas) {
		this.nbId = nbId;
		this.tbMicUnidades = tbMicUnidades;
		this.tbMicTemas = tbMicTemas;
	}

	public TbMicTemasxunidad(int nbId, TbMicUnidades tbMicUnidades,
			TbMicTemas tbMicTemas, int nbSemanasRequeridas,
			String vrModusuario, Date dtModfecha) {
		this.nbId = nbId;
		this.tbMicUnidades = tbMicUnidades;
		this.tbMicTemas = tbMicTemas;
		this.nbSemanasRequeridas = nbSemanasRequeridas;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}

	public int getNbId() {
		return this.nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public TbMicUnidades getTbMicUnidades() {
		return this.tbMicUnidades;
	}

	public void setTbMicUnidades(TbMicUnidades tbMicUnidades) {
		this.tbMicUnidades = tbMicUnidades;
	}

	public TbMicTemas getTbMicTemas() {
		return this.tbMicTemas;
	}

	public void setTbMicTemas(TbMicTemas tbMicTemas) {
		this.tbMicTemas = tbMicTemas;
	}

	public int getNbSemanasRequeridas() {
		return this.nbSemanasRequeridas;
	}

	public void setNbSemanasRequeridas(int nbSemanasRequeridas) {
		this.nbSemanasRequeridas = nbSemanasRequeridas;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

}
