package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbMicSubtemas generated by hbm2java
 */
public class TbMicSubtemas implements java.io.Serializable {

	private int nbIdsubtema;
	private TbMicTemas tbMicTemas;
	private String vrDescripcion;
	private String vrModusuario;
	private Date dtModfecha;

	public TbMicSubtemas() {
	}

	public TbMicSubtemas(int nbIdsubtema, TbMicTemas tbMicTemas) {
		this.nbIdsubtema = nbIdsubtema;
		this.tbMicTemas = tbMicTemas;
	}

	public TbMicSubtemas(int nbIdsubtema, TbMicTemas tbMicTemas,
			String vrDescripcion, String vrModusuario, Date dtModfecha) {
		this.nbIdsubtema = nbIdsubtema;
		this.tbMicTemas = tbMicTemas;
		this.vrDescripcion = vrDescripcion;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}

	public int getNbIdsubtema() {
		return this.nbIdsubtema;
	}

	public void setNbIdsubtema(int nbIdsubtema) {
		this.nbIdsubtema = nbIdsubtema;
	}

	public TbMicTemas getTbMicTemas() {
		return this.tbMicTemas;
	}

	public void setTbMicTemas(TbMicTemas tbMicTemas) {
		this.tbMicTemas = tbMicTemas;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

}
