package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbMicMateriasxpensum generated by hbm2java
 */
public class TbMicMateriasxpensum implements java.io.Serializable {

	private int nbId;
	private TbAdmMaterias tbAdmMaterias;
	private TbMicPensum tbMicPensum;
	private String vrModusuario;
	private Date dtModfecha;

	public TbMicMateriasxpensum() {
	}

	public TbMicMateriasxpensum(int nbId, TbAdmMaterias tbAdmMaterias,
			TbMicPensum tbMicPensum) {
		this.nbId = nbId;
		this.tbAdmMaterias = tbAdmMaterias;
		this.tbMicPensum = tbMicPensum;
	}

	public TbMicMateriasxpensum(int nbId, TbAdmMaterias tbAdmMaterias,
			TbMicPensum tbMicPensum, String vrModusuario, Date dtModfecha) {
		this.nbId = nbId;
		this.tbAdmMaterias = tbAdmMaterias;
		this.tbMicPensum = tbMicPensum;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}

	public int getNbId() {
		return this.nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public TbAdmMaterias getTbAdmMaterias() {
		return this.tbAdmMaterias;
	}

	public void setTbAdmMaterias(TbAdmMaterias tbAdmMaterias) {
		this.tbAdmMaterias = tbAdmMaterias;
	}

	public TbMicPensum getTbMicPensum() {
		return this.tbMicPensum;
	}

	public void setTbMicPensum(TbMicPensum tbMicPensum) {
		this.tbMicPensum = tbMicPensum;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

}
