package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbMicBibliografia generated by hbm2java
 */
public class TbMicBibliografia implements java.io.Serializable {

	private int nbIdbibliografia;
	private String vrNombre;
	private String vrSitioweb;
	private String vrIsbn;
	private String vrAutor;
	private Character blTipo;
	private String vrModusuario;
	private Date dtModfecha;
	private Set tbMicBiblioxunidads = new HashSet(0);

	
	public TbMicBibliografia() {
		super();
	}

	public TbMicBibliografia(String vrNombre, String vrSitioweb, String vrIsbn, String vrAutor, Character blTipo,
			String vrModusuario, Date dtModfecha) {
		super();
		this.vrNombre = vrNombre;
		this.vrSitioweb = vrSitioweb;
		this.vrIsbn = vrIsbn;
		this.vrAutor = vrAutor;
		this.blTipo = blTipo;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}




	public int getNbIdbibliografia() {
		return this.nbIdbibliografia;
	}

	public void setNbIdbibliografia(int nbIdbibliografia) {
		this.nbIdbibliografia = nbIdbibliografia;
	}

	public String getVrNombre() {
		return this.vrNombre;
	}

	public void setVrNombre(String vrNombre) {
		this.vrNombre = vrNombre;
	}

	public String getVrSitioweb() {
		return this.vrSitioweb;
	}

	public void setVrSitioweb(String vrSitioweb) {
		this.vrSitioweb = vrSitioweb;
	}

	public String getVrIsbn() {
		return this.vrIsbn;
	}

	public void setVrIsbn(String vrIsbn) {
		this.vrIsbn = vrIsbn;
	}

	public String getVrAutor() {
		return vrAutor;
	}

	public void setVrAutor(String vrAutor) {
		this.vrAutor = vrAutor;
	}


	public Character getBlTipo() {
		return this.blTipo;
	}

	public void setBlTipo(Character blTipo) {
		this.blTipo = blTipo;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

	public Set getTbMicBiblioxunidads() {
		return this.tbMicBiblioxunidads;
	}

	public void setTbMicBiblioxunidads(Set tbMicBiblioxunidads) {
		this.tbMicBiblioxunidads = tbMicBiblioxunidads;
	}
}
