package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbMicMicroxestado generated by hbm2java
 */
public class TbMicMicroxestado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int nbId;
	private TbMicEstado tbMicEstado;
	private Date dtFecha;
	private TbMicMicrocurriculo tbMicMicrocurriculo;
	private TbAdmPersona tbAdmResponsable;
	private String vrModusuario;
	private Date dtModfecha;

	
	public TbMicMicroxestado() {
		super();
	}

	public TbMicMicroxestado(TbMicEstado tbMicEstado, TbMicMicrocurriculo tbMicMicrocurriculo) {
		this.tbMicEstado = tbMicEstado;
		this.tbMicMicrocurriculo = tbMicMicrocurriculo;
	}

	public TbMicMicroxestado(TbMicEstado tbMicEstado, Date dtFecha,
			TbMicMicrocurriculo tbMicMicrocurriculo,
			TbAdmPersona tbAdmResponsable, String vrModusuario, Date dtModfecha) {
		super();
		this.tbMicEstado = tbMicEstado;
		this.dtFecha = dtFecha;
		this.tbMicMicrocurriculo = tbMicMicrocurriculo;
		this.tbAdmResponsable = tbAdmResponsable;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}

	public int getNbId() {
		return this.nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public TbMicEstado getTbMicEstado() {
		return this.tbMicEstado;
	}

	public void setTbMicEstado(TbMicEstado tbMicEstado) {
		this.tbMicEstado = tbMicEstado;
	}

	public TbMicMicrocurriculo getTbMicMicrocurriculo() {
		return this.tbMicMicrocurriculo;
	}

	public void setTbMicMicrocurriculo(
			TbMicMicrocurriculo tbMicMicrocurriculo) {
		this.tbMicMicrocurriculo = tbMicMicrocurriculo;
	}

	public Date getDtFecha() {
		return dtFecha;
	}

	public void setDtFecha(Date dtFecha) {
		this.dtFecha = dtFecha;
	}

	public TbAdmPersona getTbAdmResponsable() {
		return tbAdmResponsable;
	}

	public void setTbAdmResponsable(TbAdmPersona tbAdmResponsable) {
		this.tbAdmResponsable = tbAdmResponsable;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModusuario) {
		this.dtModfecha = dtModusuario;
	}

}
