package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbMicObjetivosxmicro generated by hbm2java
 */
public class TbMicObjetivosxmicro implements java.io.Serializable {

	private int nbId;
	private TbMicObjetivos tbMicObjetivos;
	private TbMicMicrocurriculos tbMicMicrocurriculos;
	private String vrModusuario;
	private Date dtModfecha;

	public TbMicObjetivosxmicro() {
	}

	public TbMicObjetivosxmicro(int nbId, TbMicObjetivos tbMicObjetivos,
			TbMicMicrocurriculos tbMicMicrocurriculos) {
		this.nbId = nbId;
		this.tbMicObjetivos = tbMicObjetivos;
		this.tbMicMicrocurriculos = tbMicMicrocurriculos;
	}

	public TbMicObjetivosxmicro(int nbId, TbMicObjetivos tbMicObjetivos,
			TbMicMicrocurriculos tbMicMicrocurriculos, String vrModusuario,
			Date dtModfecha) {
		this.nbId = nbId;
		this.tbMicObjetivos = tbMicObjetivos;
		this.tbMicMicrocurriculos = tbMicMicrocurriculos;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}

	public int getNbId() {
		return this.nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public TbMicObjetivos getTbMicObjetivos() {
		return this.tbMicObjetivos;
	}

	public void setTbMicObjetivos(TbMicObjetivos tbMicObjetivos) {
		this.tbMicObjetivos = tbMicObjetivos;
	}

	public TbMicMicrocurriculos getTbMicMicrocurriculos() {
		return this.tbMicMicrocurriculos;
	}

	public void setTbMicMicrocurriculos(
			TbMicMicrocurriculos tbMicMicrocurriculos) {
		this.tbMicMicrocurriculos = tbMicMicrocurriculos;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

}
