package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbMicMicroxestado generated by hbm2java
 */
public class TbMicMicroxestado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int nbId;
	private TbMicEstados tbMicEstados;
	private TbMicMicrocurriculos tbMicMicrocurriculos;
	private String vrModusuario;
	private Date dtModfecha;

	public TbMicMicroxestado() {
	}

	public TbMicMicroxestado(int nbId, TbMicEstados tbMicEstados,
			TbMicMicrocurriculos tbMicMicrocurriculos) {
		this.nbId = nbId;
		this.tbMicEstados = tbMicEstados;
		this.tbMicMicrocurriculos = tbMicMicrocurriculos;
	}

	public TbMicMicroxestado(int nbId, TbMicEstados tbMicEstados,
			TbMicMicrocurriculos tbMicMicrocurriculos, String vrModusuario,
			Date dtModfecha) {
		this.nbId = nbId;
		this.tbMicEstados = tbMicEstados;
		this.tbMicMicrocurriculos = tbMicMicrocurriculos;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}

	public int getNbId() {
		return this.nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public TbMicEstados getTbMicEstados() {
		return this.tbMicEstados;
	}

	public void setTbMicEstados(TbMicEstados tbMicEstados) {
		this.tbMicEstados = tbMicEstados;
	}

	public TbMicMicrocurriculos getTbMicMicrocurriculos() {
		return this.tbMicMicrocurriculos;
	}

	public void setTbMicMicrocurriculos(
			TbMicMicrocurriculos tbMicMicrocurriculos) {
		this.tbMicMicrocurriculos = tbMicMicrocurriculos;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModusuario) {
		this.dtModfecha = dtModusuario;
	}

}
