package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbMicAutores generated by hbm2java
 */
public class TbMicAutor implements java.io.Serializable {

	private int nbIdautor;
	private String vrNombres;
	private String vrApellidos;
	private int nbPais;
	private String vrModusuario;
	private Date dtModfecha;
	private Set tbMicAutorxbiblios = new HashSet(0);

	public TbMicAutor() {
	}

	public TbMicAutor(int nbIdautor, int nbPais) {
		this.nbIdautor = nbIdautor;
		this.nbPais = nbPais;
	}

	public TbMicAutor(int nbIdautor, String vrNombres,
			String vrApellidos, int nbPais, String vrModusuario,
			Date dtModfecha, Set tbMicAutorxbiblios) {
		this.nbIdautor = nbIdautor;
		this.vrNombres = vrNombres;
		this.vrApellidos = vrApellidos;
		this.nbPais = nbPais;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
		this.tbMicAutorxbiblios = tbMicAutorxbiblios;
	}

	public int getNbIdautor() {
		return this.nbIdautor;
	}

	public void setNbIdautor(int nbIdautor) {
		this.nbIdautor = nbIdautor;
	}

	public String getVrNombres() {
		return this.vrNombres;
	}

	public void setVrNombres(String vrNombres) {
		this.vrNombres = vrNombres;
	}

	public String getVrApellidos() {
		return this.vrApellidos;
	}

	public void setVrApellidos(String vrApellidos) {
		this.vrApellidos = vrApellidos;
	}

	public int getNbPais() {
		return this.nbPais;
	}

	public void setNbPais(int nbPais) {
		this.nbPais = nbPais;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

	public Set getTbMicAutorxbiblios() {
		return this.tbMicAutorxbiblios;
	}

	public void setTbMicAutorxbiblios(Set tbMicAutorxbiblios) {
		this.tbMicAutorxbiblios = tbMicAutorxbiblios;
	}

}
