package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbMicBiblioxunidad generated by hbm2java
 */
public class TbMicBiblioxunidad implements java.io.Serializable {

	private int nbId;
	private TbMicBibliografia tbMicBibliografia;
	private TbMicUnidades tbMicUnidades;
	private String vrModusuario;
	private Date dtModfecha;

	public TbMicBiblioxunidad() {
	}

	public TbMicBiblioxunidad(int nbId,
			TbMicBibliografia tbMicBibliografia, TbMicUnidades tbMicUnidades) {
		this.nbId = nbId;
		this.tbMicBibliografia = tbMicBibliografia;
		this.tbMicUnidades = tbMicUnidades;
	}

	public TbMicBiblioxunidad(int nbId,
			TbMicBibliografia tbMicBibliografia, TbMicUnidades tbMicUnidades,
			String vrModusuario, Date dtModfecha) {
		this.nbId = nbId;
		this.tbMicBibliografia = tbMicBibliografia;
		this.tbMicUnidades = tbMicUnidades;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}

	public int getNbId() {
		return this.nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public TbMicBibliografia getTbMicBibliografia() {
		return this.tbMicBibliografia;
	}

	public void setTbMicBibliografia(TbMicBibliografia tbMicBibliografia) {
		this.tbMicBibliografia = tbMicBibliografia;
	}

	public TbMicUnidades getTbMicUnidades() {
		return this.tbMicUnidades;
	}

	public void setTbMicUnidades(TbMicUnidades tbMicUnidades) {
		this.tbMicUnidades = tbMicUnidades;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

}
