package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbMicTemas generated by hbm2java
 */
public class TbMicTema implements java.io.Serializable {

	private int nbIdtema;
	private String vrDescripcion;
	private String vrModusuario;
	private Date dtModfecha;
	private Set tbMicSubtemases = new HashSet(0);
	private Set tbMicTemasxunidads = new HashSet(0);


	public TbMicTema(String vrDescripcion, String vrModusuario,
			Date dtModfecha) {
		super();
		this.nbIdtema = nbIdtema;
		this.vrDescripcion = vrDescripcion;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}



	public TbMicTema(int nbIdtema, String vrDescripcion,
			String vrModusuario, Date dtModfecha, Set tbMicSubtemases,
			Set tbMicTemasxunidads) {
		this.nbIdtema = nbIdtema;
		this.vrDescripcion = vrDescripcion;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
		this.tbMicSubtemases = tbMicSubtemases;
		this.tbMicTemasxunidads = tbMicTemasxunidads;
	}

	public int getNbIdtema() {
		return this.nbIdtema;
	}

	public void setNbIdtema(int nbIdtema) {
		this.nbIdtema = nbIdtema;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

	public Set getTbMicSubtemases() {
		return this.tbMicSubtemases;
	}

	public void setTbMicSubtemases(Set tbMicSubtemases) {
		this.tbMicSubtemases = tbMicSubtemases;
	}

	public Set getTbMicTemasxunidads() {
		return this.tbMicTemasxunidads;
	}

	public void setTbMicTemasxunidads(Set tbMicTemasxunidads) {
		this.tbMicTemasxunidads = tbMicTemasxunidads;
	}

}
