package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbMicMicroxestado generated by hbm2java
 */
public class TbMicMicroxestado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int nbId;
	private TbMicEstado tbMicEstado;
	private TbMicMicrocurriculo tbMicMicrocurriculo;
	private String vrModusuario;
	private Date dtModfecha;

	public TbMicMicroxestado() {
	}

	public TbMicMicroxestado(int nbId, TbMicEstado tbMicEstado,
			TbMicMicrocurriculo tbMicMicrocurriculo) {
		this.nbId = nbId;
		this.tbMicEstado = tbMicEstado;
		this.tbMicMicrocurriculo = tbMicMicrocurriculo;
	}

	public TbMicMicroxestado(int nbId, TbMicEstado tbMicEstado,
			TbMicMicrocurriculo tbMicMicrocurriculo, String vrModusuario,
			Date dtModfecha) {
		this.nbId = nbId;
		this.tbMicEstado = tbMicEstado;
		this.tbMicMicrocurriculo = tbMicMicrocurriculo;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}

	public int getNbId() {
		return this.nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public TbMicEstado getTbMicEstado() {
		return this.tbMicEstado;
	}

	public void setTbMicEstado(TbMicEstado tbMicEstado) {
		this.tbMicEstado = tbMicEstado;
	}

	public TbMicMicrocurriculo getTbMicMicrocurriculo() {
		return this.tbMicMicrocurriculo;
	}

	public void setTbMicMicrocurriculo(
			TbMicMicrocurriculo tbMicMicrocurriculo) {
		this.tbMicMicrocurriculo = tbMicMicrocurriculo;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModusuario) {
		this.dtModfecha = dtModusuario;
	}

}
