package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * TbMicMicrocurriculos generated by hbm2java
 */
public class TbMicMicrocurriculo implements java.io.Serializable {

	private String vrIdmicrocurriculo;
	private TbAdmMateria tbAdmMateria;
	private TbAdmSemestre tbAdmSemestre;
	private String vrProposito;
	private String vrJustificacion;
	private String vrResumen;
	private TbAdmPersona tbAdmPersona;
	private String vrModusuario;
	private Date dtModfecha;
	private Set tbMicObjetivosxmicros = new HashSet(0);
	private Set tbMicUnidadesxmicros = new HashSet(0);
	private Set tbMicMicroxestados = new HashSet(0);

	public TbMicMicrocurriculo() {
	}

	public TbMicMicrocurriculo(String vrIdmicrocurriculo,
			TbAdmMateria tbAdmMateria, TbAdmSemestre tbAdmSemestre,
			String vrProposito, String vrJustificacion, String vrResumen,
			TbAdmPersona tbAdmPersona, String vrModusuario, Date dtModfecha,
			Set tbMicObjetivosxmicros, Set tbMicUnidadesxmicros,
			Set tbMicMicroxestados) {
		super();
		this.vrIdmicrocurriculo = vrIdmicrocurriculo;
		this.tbAdmMateria = tbAdmMateria;
		this.tbAdmSemestre = tbAdmSemestre;
		this.vrProposito = vrProposito;
		this.vrJustificacion = vrJustificacion;
		this.vrResumen = vrResumen;
		this.tbAdmPersona = tbAdmPersona;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
		this.tbMicObjetivosxmicros = tbMicObjetivosxmicros;
		this.tbMicUnidadesxmicros = tbMicUnidadesxmicros;
		this.tbMicMicroxestados = tbMicMicroxestados;
	}

	public TbMicMicrocurriculo(String vrIdmicrocurriculo,
			TbAdmMateria tbAdmMateria, TbAdmSemestre tbAdmSemestre,
			String vrProposito, String vrJustificacion, String vrResumen,
			TbAdmPersona tbAdmPersona, String vrModusuario, Date dtModfecha) {
		super();
		this.vrIdmicrocurriculo = vrIdmicrocurriculo;
		this.tbAdmMateria = tbAdmMateria;
		this.tbAdmSemestre = tbAdmSemestre;
		this.vrProposito = vrProposito;
		this.vrJustificacion = vrJustificacion;
		this.vrResumen = vrResumen;
		this.tbAdmPersona = tbAdmPersona;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}

	public String getVrIdmicrocurriculo() {
		return this.vrIdmicrocurriculo;
	}

	public void setVrIdmicrocurriculo(String vrIdmicrocurriculo) {
		this.vrIdmicrocurriculo = vrIdmicrocurriculo;
	}

	public TbAdmMateria getTbAdmMateria() {
		return this.tbAdmMateria;
	}

	public void setTbAdmMateria(TbAdmMateria tbAdmMateria) {
		this.tbAdmMateria = tbAdmMateria;
	}	

	public TbAdmSemestre getTbAdmSemestre() {
		return tbAdmSemestre;
	}

	public void setTbAdmSemestre(TbAdmSemestre tbAdmSemestre) {
		this.tbAdmSemestre = tbAdmSemestre;
	}

	public String getVrResumen() {
		return this.vrResumen;
	}

	public void setVrResumen(String vrResumen) {
		this.vrResumen = vrResumen;
	}

	public TbAdmPersona getTbAdmPersona() {
		return tbAdmPersona;
	}

	public void setTbAdmPersona(TbAdmPersona tbAdmPersona) {
		this.tbAdmPersona = tbAdmPersona;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

	public Set getTbMicObjetivosxmicros() {
		return this.tbMicObjetivosxmicros;
	}

	public void setTbMicObjetivosxmicros(Set tbMicObjetivosxmicros) {
		this.tbMicObjetivosxmicros = tbMicObjetivosxmicros;
	}

	public Set getTbMicUnidadesxmicros() {
		return this.tbMicUnidadesxmicros;
	}

	public void setTbMicUnidadesxmicros(Set tbMicUnidadesxmicros) {
		this.tbMicUnidadesxmicros = tbMicUnidadesxmicros;
	}

	public Set getTbMicMicroxestados() {
		return this.tbMicMicroxestados;
	}

	public void setTbMicMicroxestados(Set tbMicMicroxestados) {
		this.tbMicMicroxestados = tbMicMicroxestados;
	}

	public String getVrProposito() {
		return vrProposito;
	}

	public void setVrProposito(String vrProposito) {
		this.vrProposito = vrProposito;
	}

	public String getVrJustificacion() {
		return vrJustificacion;
	}

	public void setVrJustificacion(String vrJustificacion) {
		this.vrJustificacion = vrJustificacion;
	}

}
