package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbMicUnidadesxmicro generated by hbm2java
 */
public class TbMicUnidadxmicro implements java.io.Serializable {

	private int nbId;
	private TbMicUnidad tbMicUnidad;
	private TbMicMicrocurriculo tbMicMicrocurriculo;
	private String vrModusuario;
	private Date dtModfecha;


	public TbMicUnidadxmicro(TbMicUnidad tbMicUnidad, TbMicMicrocurriculo tbMicMicrocurriculo) {
		this.tbMicUnidad = tbMicUnidad;
		this.tbMicMicrocurriculo = tbMicMicrocurriculo;
	}

	public TbMicUnidadxmicro(TbMicUnidad tbMicUnidad, TbMicMicrocurriculo tbMicMicrocurriculo, 
			String vrModusuario, Date dtModfecha) {
		this.tbMicUnidad = tbMicUnidad;
		this.tbMicMicrocurriculo = tbMicMicrocurriculo;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}

	public int getNbId() {
		return this.nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public TbMicUnidad getTbMicUnidad() {
		return this.tbMicUnidad;
	}

	public void setTbMicUnidad(TbMicUnidad tbMicUnidad) {
		this.tbMicUnidad = tbMicUnidad;
	}

	public TbMicMicrocurriculo getTbMicMicrocurriculo() {
		return this.tbMicMicrocurriculo;
	}

	public void setTbMicMicrocurriculo(
			TbMicMicrocurriculo tbMicMicrocurriculo) {
		this.tbMicMicrocurriculo = tbMicMicrocurriculo;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

}
