package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbMicPensum generated by hbm2java
 */
public class TbMicPensum implements java.io.Serializable {

	private int nbIdpensum;
	private String vrDescripcion;
	private Date dtFechainicio;
	private Date dtFechafin;
	private String vrModusuario;
	private Date dtModfecha;
	private Set tbMicMateriasxpensums = new HashSet(0);

	public TbMicPensum() {
	}

	public TbMicPensum(int nbIdpensum) {
		this.nbIdpensum = nbIdpensum;
	}

	public TbMicPensum(int nbIdpensum, String vrDescripcion,
			Date dtFechainicio, Date dtFechafin, String vrModusuario,
			Date dtModfecha, Set tbMicMateriasxpensums) {
		this.nbIdpensum = nbIdpensum;
		this.vrDescripcion = vrDescripcion;
		this.dtFechainicio = dtFechainicio;
		this.dtFechafin = dtFechafin;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
		this.tbMicMateriasxpensums = tbMicMateriasxpensums;
	}

	public int getNbIdpensum() {
		return this.nbIdpensum;
	}

	public void setNbIdpensum(int nbIdpensum) {
		this.nbIdpensum = nbIdpensum;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}

	public Date getDtFechainicio() {
		return this.dtFechainicio;
	}

	public void setDtFechainicio(Date dtFechainicio) {
		this.dtFechainicio = dtFechainicio;
	}

	public Date getDtFechafin() {
		return this.dtFechafin;
	}

	public void setDtFechafin(Date dtFechafin) {
		this.dtFechafin = dtFechafin;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

	public Set getTbMicMateriasxpensums() {
		return this.tbMicMateriasxpensums;
	}

	public void setTbMicMateriasxpensums(Set tbMicMateriasxpensums) {
		this.tbMicMateriasxpensums = tbMicMateriasxpensums;
	}

}
