package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbMicMicrocurriculos generated by hbm2java
 */
public class TbMicMicrocurriculos implements java.io.Serializable {

	private String vrIdmicrocurriculo;
	private TbAdmMaterias tbAdmMaterias;
	private String vrResumen;
	private String vrMetodologia;
	private int nbSemestre;
	private String vrResponsable;
	private String vrModusuario;
	private Date dtModfecha;
	private Set tbMicMicroxsemestres = new HashSet(0);
	private Set tbMicObjetivosxmicros = new HashSet(0);
	private Set tbMicUnidadesxmicros = new HashSet(0);
	private Set tbMicMicroxestados = new HashSet(0);

	public TbMicMicrocurriculos() {
	}

	public TbMicMicrocurriculos(String vrIdmicrocurriculo,
			TbAdmMaterias tbAdmMaterias, int nbSemestre,
			String vrResponsable, String vrModusuario) {
		this.vrIdmicrocurriculo = vrIdmicrocurriculo;
		this.tbAdmMaterias = tbAdmMaterias;
		this.nbSemestre = nbSemestre;
		this.vrResponsable = vrResponsable;
		this.vrModusuario = vrModusuario;
	}

	public TbMicMicrocurriculos(String vrIdmicrocurriculo,
			TbAdmMaterias tbAdmMaterias, String vrResumen,
			String vrMetodologia, int nbSemestre, String vrResponsable,
			String vrModusuario, Date dtModfecha, Set tbMicMicroxsemestres,
			Set tbMicObjetivosxmicros, Set tbMicUnidadesxmicros,
			Set tbMicMicroxestados) {
		this.vrIdmicrocurriculo = vrIdmicrocurriculo;
		this.tbAdmMaterias = tbAdmMaterias;
		this.vrResumen = vrResumen;
		this.vrMetodologia = vrMetodologia;
		this.nbSemestre = nbSemestre;
		this.vrResponsable = vrResponsable;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
		this.tbMicMicroxsemestres = tbMicMicroxsemestres;
		this.tbMicObjetivosxmicros = tbMicObjetivosxmicros;
		this.tbMicUnidadesxmicros = tbMicUnidadesxmicros;
		this.tbMicMicroxestados = tbMicMicroxestados;
	}

	public String getVrIdmicrocurriculo() {
		return this.vrIdmicrocurriculo;
	}

	public void setVrIdmicrocurriculo(String vrIdmicrocurriculo) {
		this.vrIdmicrocurriculo = vrIdmicrocurriculo;
	}

	public TbAdmMaterias getTbAdmMaterias() {
		return this.tbAdmMaterias;
	}

	public void setTbAdmMaterias(TbAdmMaterias tbAdmMaterias) {
		this.tbAdmMaterias = tbAdmMaterias;
	}

	public String getVrResumen() {
		return this.vrResumen;
	}

	public void setVrResumen(String vrResumen) {
		this.vrResumen = vrResumen;
	}

	public String getVrMetodologia() {
		return this.vrMetodologia;
	}

	public void setVrMetodologia(String vrMetodologia) {
		this.vrMetodologia = vrMetodologia;
	}

	public int getNbSemestre() {
		return this.nbSemestre;
	}

	public void setNbSemestre(int nbSemestre) {
		this.nbSemestre = nbSemestre;
	}

	public String getVrResponsable() {
		return this.vrResponsable;
	}

	public void setVrResponsable(String vrResponsable) {
		this.vrResponsable = vrResponsable;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

	public Set getTbMicMicroxsemestres() {
		return this.tbMicMicroxsemestres;
	}

	public void setTbMicMicroxsemestres(Set tbMicMicroxsemestres) {
		this.tbMicMicroxsemestres = tbMicMicroxsemestres;
	}

	public Set getTbMicObjetivosxmicros() {
		return this.tbMicObjetivosxmicros;
	}

	public void setTbMicObjetivosxmicros(Set tbMicObjetivosxmicros) {
		this.tbMicObjetivosxmicros = tbMicObjetivosxmicros;
	}

	public Set getTbMicUnidadesxmicros() {
		return this.tbMicUnidadesxmicros;
	}

	public void setTbMicUnidadesxmicros(Set tbMicUnidadesxmicros) {
		this.tbMicUnidadesxmicros = tbMicUnidadesxmicros;
	}

	public Set getTbMicMicroxestados() {
		return this.tbMicMicroxestados;
	}

	public void setTbMicMicroxestados(Set tbMicMicroxestados) {
		this.tbMicMicroxestados = tbMicMicroxestados;
	}

}
