package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbMicUnidadesxmicro generated by hbm2java
 */
public class TbMicUnidadesxmicro implements java.io.Serializable {

	private int nbId;
	private TbMicUnidades tbMicUnidades;
	private TbMicMicrocurriculos tbMicMicrocurriculos;
	private String vrModusuario;
	private Date dtModfecha;

	public TbMicUnidadesxmicro() {
	}

	public TbMicUnidadesxmicro(int nbId, TbMicUnidades tbMicUnidades,
			TbMicMicrocurriculos tbMicMicrocurriculos) {
		this.nbId = nbId;
		this.tbMicUnidades = tbMicUnidades;
		this.tbMicMicrocurriculos = tbMicMicrocurriculos;
	}

	public TbMicUnidadesxmicro(int nbId, TbMicUnidades tbMicUnidades,
			TbMicMicrocurriculos tbMicMicrocurriculos, String vrModusuario,
			Date dtModfecha) {
		this.nbId = nbId;
		this.tbMicUnidades = tbMicUnidades;
		this.tbMicMicrocurriculos = tbMicMicrocurriculos;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}

	public int getNbId() {
		return this.nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public TbMicUnidades getTbMicUnidades() {
		return this.tbMicUnidades;
	}

	public void setTbMicUnidades(TbMicUnidades tbMicUnidades) {
		this.tbMicUnidades = tbMicUnidades;
	}

	public TbMicMicrocurriculos getTbMicMicrocurriculos() {
		return this.tbMicMicrocurriculos;
	}

	public void setTbMicMicrocurriculos(
			TbMicMicrocurriculos tbMicMicrocurriculos) {
		this.tbMicMicrocurriculos = tbMicMicrocurriculos;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

}
