package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbMicAutorxbiblio generated by hbm2java
 */
public class TbMicAutorxbiblio implements java.io.Serializable {

	private int nbId;
	private TbMicBibliografia tbMicBibliografia;
	private TbMicAutores tbMicAutores;
	private String vrModusuario;
	private Date dtModfecha;

	public TbMicAutorxbiblio() {
	}

	public TbMicAutorxbiblio(int nbId,
			TbMicBibliografia tbMicBibliografia, TbMicAutores tbMicAutores) {
		this.nbId = nbId;
		this.tbMicBibliografia = tbMicBibliografia;
		this.tbMicAutores = tbMicAutores;
	}

	public TbMicAutorxbiblio(int nbId,
			TbMicBibliografia tbMicBibliografia, TbMicAutores tbMicAutores,
			String vrModusuario, Date dtModfecha) {
		this.nbId = nbId;
		this.tbMicBibliografia = tbMicBibliografia;
		this.tbMicAutores = tbMicAutores;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}

	public int getNbId() {
		return this.nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public TbMicBibliografia getTbMicBibliografia() {
		return this.tbMicBibliografia;
	}

	public void setTbMicBibliografia(TbMicBibliografia tbMicBibliografia) {
		this.tbMicBibliografia = tbMicBibliografia;
	}

	public TbMicAutores getTbMicAutores() {
		return this.tbMicAutores;
	}

	public void setTbMicAutores(TbMicAutores tbMicAutores) {
		this.tbMicAutores = tbMicAutores;
	}

	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}

}
