package com.udea.proint1.microcurriculo.dto;

// Generated 21/10/2014 12:17:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbMicEvaluaciones generated by hbm2java
 */
public class TbMicEvaluacion implements java.io.Serializable {

	private int nbIdevaluacion;
	private String vrDescripcion;
	private String vrModusuario;
	private Date dtModfecha;
	private Set tbMicMicroxevaluaciones = new HashSet(0);

	public TbMicEvaluacion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}
	
	public TbMicEvaluacion(String vrDescripcion, String vrModusuario, Date dtModfecha) {
		this.vrDescripcion = vrDescripcion;
		this.vrModusuario = vrModusuario;
		this.dtModfecha = dtModfecha;
	}

	public int getNbIdevaluacion() {
		return this.nbIdevaluacion;
	}

	public void setNbIdevaluacion(int nbIdevaluacion) {
		this.nbIdevaluacion = nbIdevaluacion;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}
	
	public String getVrModusuario() {
		return this.vrModusuario;
	}

	public void setVrModusuario(String vrModusuario) {
		this.vrModusuario = vrModusuario;
	}

	public Date getDtModfecha() {
		return this.dtModfecha;
	}

	public void setDtModfecha(Date dtModfecha) {
		this.dtModfecha = dtModfecha;
	}	
	
	public Set getTbMicMicroxevaluaciones() {
		return this.tbMicMicroxevaluaciones;
	}

	public void setTbMicMicroxevaluaciones(Set tbMicMicroxevaluaciones) {
		this.tbMicMicroxevaluaciones = tbMicMicroxevaluaciones;
	}

}
